schema: http
port: 8089
ssl_certificate:
ssl_certificate_key:
health_check: true
# ping 检查需要root
# ping_health_check: false
health_check_interval: 3
max_allowed: 100
location:
  - pattern: /
    proxy_pass:
      - "http://127.0.0.1:1331"
      - "http://127.0.0.1:1332"
      - "http://127.0.0.1:1333"
      - "http://127.0.0.1:1334"
    # round-robin random ip-hash p2c least-load consistent-hash consistent-hash-with-load
    balance_mode: random
